### PR TITLE
Readme logo update

### PR DESCRIPTION
**Pull request by dylanatsmith**
### Summary

Takes advantage of GitHub’s newly supported functionality to show/hide images in Markdown depending on which GH theme is served as per user settings.

* [Feature documentaion](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)
* [Community request thread](https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/77)

Further optimises the solution to https://github.com/github/view_component/issues/1134 shipped in https://github.com/github/view_component/pull/1143.

Note: There doesn't seem to be a way, at least in GFM, to specify image size. So using exising assets they'll be full-width unless we create smaller ones for this purpose.

### CODE REVIEW

**Comment by Spone** [comment]
Great that this feature shipped!

> Note: There doesn't seem to be a way, at least in GFM, to specify image size. So using exising assets they'll be full-width unless we create smaller ones for this purpose.

It's a bit large for the README, don't you think?

image

What about changing the `width="735" height="84" viewBox="0 0 735 84"` values in the existing assets? Since it's SVG there will be no quality loss if people want to use them at larger size in other contexts.

**Comment by dylanatsmith** [comment]
It's nearly comical on desktop for sure.

Changing the canonical SVG is an option. I don’t _think_ there’d be any side effects. I don’t love the idea of adding those attributes to satisfy this one use case, just on principle, but I’m not opposed.

I think we do one of the following:
1. Leave it full-width in the readme
2. Change the size of the canonical SVG
3. Add additional, readme-specific assets like we’re currently using

I’m leaning toward option 3 at the moment but I’m open.

**Comment by BlakeWilliams** [comment]
I'm 👍 on option 3, using assets specifically for the README makes sense to me.

**Comment by joelhawksley** [comment]
I'm fine with option 3 as well 👍🏻

**Review by joelhawksley — APPROVED** [review]

**Pull request merged**
