### PR TITLE
[ADR] Remove suffix from naming conventions

### LINKED ISSUE #670: Remove the Component suffix from components
As we've written and used components the `Component` suffix has been questioned a few times. Looking at current uses of components, it looks like the namespaces used are unique even when the `Component` suffix is removed. I think this is due to following the naming convention of views, which is to use the plural paths in the namespace. e.g. `users/index.html.erb` -> `Users::IndexComponent`/`Users::Index`.

Lately I've been thinking about components as "models that return markup". Models don't have a suffix (and neither do views, although they are usually templates), so maybe components shouldn't either?

Here's the pro's and con's I can think of at the moment:

* **Pro**: Less boilerplate and better readability. No more `render Primer::LinkComponent.new`, we can now call `render Primer::Link.new`. Once you learn that components are objects that can be rendered, the `Component` suffix loses a lot of its value.
* **Pro**: Component names now completely align with the `views` naming conventions. This will make it easier to put components in the `views` directory if we go down that path.
* **Con**: It's no longer immediately clear that your class/object is a component.

### PR DESCRIPTION
**Pull request by joelhawksley**
[closes #670]

_Please read this pull request as a **proposal** that can and **should** change._

### Summary

I think we should move away from naming ViewComponents with the `-Component` suffix.

I've included documentation in the form of an Architectural Decision Record. I'd love to see us use that document as the grounds of debate for this proposal. 

Assuming we can agree on this change, I will take on the work of updating the project to follow these guidelines.

### CODE REVIEW

**Comment by joelhawksley** [comment]
@jaredcwhite I'd love to hear your thoughts on this change, as you had commented on #670.

**Comment by jonspalmer** [comment]
I'm mostly unconvinced by this change. It's very un_railsy.

Consider that you could have this set of files:

app/components/users_component.rb
app/controllers/users_controller.rb
app/helpers/users_helper.rb

that seems pretty reasonable and consistent. 

What if everyone made the choice described here? We have three users.rb files different only because of directory that they're in? It probably also breaks the world as there are no namespaces. This decision documented here is only really possible because Rails convention is to use suffixes.

**Comment by Spone** [comment]
I don't have a clear opinion yet. I hear the arguments made in the ADR. I definitely agree with @jonspalmer considerations.

I would add that:
- Not migrating existing components to the new naming scheme would mean cohabitation between `OldStuffComponent` and `NewStuff` = confusion. So migration is nearly mandatory (unless you don't plan to add new components to your project).
- The changes required to migrate will probably be a quick search-and-replace (in source code) and potentially a LOT of folders and files to rename. Could a migration task be provided?

> This is due to following the naming convention of views, which is to use the plural paths in the namespace. e.g. `users/index.html.erb` -> `Users::IndexComponent`/`Users::Index`.

- I don't know if it's necessarily the case in most projects using ViewComponent. It's not in mine :smile: 
- A quick diagnostics task could be helpful to test if the migration would create collisions in any given project. It may provide useful insights for this decision?

**Comment by boardfish** [comment]
One thing I've been doing so far is keeping all components namespaced based on their purpose. As I've previously mentioned elsewhere, I'm following Atomic Design and using `A`toms, `M`olecules, and `O`rganisms. This is good for my use case because it's easily recognizable.

For most projects, the divide will be simpler than that, though - ViewComponents will be used for both components and views, so appropriate namespaces for those would be good. `View::Users::Index` and `Component::Button` would be potential examples. However, in the case of the `Component` namespace, we lose this benefit:

> Less boilerplate and better readability. [...] Once you learn that components are objects that can be rendered, the `Component` suffix loses a lot of its value.

Another question I have is how layouts might be considered under this structure.

**Review by boardfish — COMMENTED** [review]
I worry that components being part of the top-level namespace might lead to conflicts without some good guidelines around how to name components and views.

One thing I've been doing so far is keeping all components namespaced based on their purpose. As I've previously mentioned elsewhere, I'm following Atomic Design and using `A`toms, `M`olecules, and `O`rganisms. This is good for my use case because it's easily recognizable, and keeps components contained to namespaces to prevent clashes. I plan to do the same with layouts and views.

For a lot of projects, `A`/`M`/`O` modules aren't necessary as that sort of granularity might cause more friction than good. They'll potentially have three main uses for ViewComponent: global components, views, and layouts. Theoretically, these could each have a namespace - let's say `Component`, `View`, and `Layout` to start with. However, because of the length of these names (particularly `Component`), we lose the benefit of making it quicker to call components, which is arguably the main goal of this ADR.

My gut tells me abbreviating the layouts (e.g. `V`iew and `C`omponent) would be unconventional, but I'll throw the idea out there regardless. Either way, namespaces with short (<5 character) names are worth consideration to solve for this IMO.

**Comment by joelhawksley** [comment]
@spone @jonspalmer @boardfish thank you for the thoughtful feedback. You've helped me think more critically about this proposed change and understand how it could negatively affect others.

A different approach might make more sense: allowing the generators not to use the suffix as a configuration option turned off by default to preserve the existing behavior.

The motivation for this change was the experience we've had with Primer ViewComponents, where we've decided to remove the `-Component` suffix. However, all of those ViewComponents exist within the `Primer` namespace.

**Comment by boardfish** [comment]
I still feel that the Component suffix should be abandoned entirely for the reasons described in the ADR. ViewComponent feels like a significant architecture decision in a Rails app — I don't believe folks that use the library will do it by halves. I expect a lot of components will make up the frontend at any level, and that means most users of the library will be likely to face the same issue, so the suffix still being present by default is potentially likely to cause friction. Disabling it with a flag would be a good first step to ease that pain for current users.

A namespace or something to that effect probably feels like the better long-term solution to me, though. While folks might not always be intending to make their own design system, I think using a namespace makes a lot of sense for the reasons I've described already. But it'll be difficult to decide on a sane default that brings the intended benefits of the ADR, maintains the ease of working with the library in the first instance, and considers the layers for which components can play a role.

I wonder if it'd be good to discuss this kind of thing on a call sometime.

**Comment by boardfish** [comment]
I still feel that the Component suffix should be abandoned entirely for the reasons described in the ADR. ViewComponent feels like a significant architecture decision in a Rails app — I don't believe folks that use the library will do it by halves. I expect a lot of components will make up the frontend at any level, and that means most users of the library will be likely to face the same issue, so the suffix still being present by default is potentially likely to cause friction. Disabling it with a flag would be a good first step to ease that pain for current users.

A namespace or something to that effect probably feels like the better long-term solution to me, though. While folks might not always be intending to make their own design system, I think using a namespace makes a lot of sense for the reasons I've described already. But it'll be difficult to decide on a sane default that brings the intended benefits of the ADR, maintains the ease of working with the library in the first instance, and considers the layers for which components can play a role.

I wonder if it'd be good to discuss this kind of thing on a call sometime.

**Comment by jonspalmer** [comment]
@joelhawksley I agree that you suggestion would be a great one. 

I agree with you that in larger systems namespaces are likely and can help. However, an extracted design system like Primer is not really the norm. Even if I was building out a design system in an app its not a given that I'd pick a namespace just for the design system. I might/have chosen other patterns to organize and group the code. Also even with a design system there will likely be components the aren't part of it but support some specific function. In my experience those components get namespaces under their functional area where collisions are more likely without the Component suffix.

@boardfish I disagree with the statement that folks won't do things by halves. Anyone with an existing Rails codebase wanting to try out ViewComponents is very likely to try it in a fewer places and see how it fits. They might have hundreds or thousands of views and partials to convert. That might take months or years depending on the organizational priorities. Its imperative IMO to minimize the experimentation cost for those folks. Having to worry about name spacing that components to avoid naming collisions is only going to be an impediment to adoption.

@joelhawksley One thought - its always struck me as unexpected to have to include the component suffix in the template file names (because Rails does not require `_controller` in regular views). Is it an option to drop that requirement? I actually thing that would make a big difference and make ViewComponents more consistent with Rails conventions.

**Comment by boardfish** [comment]
Those are some good points @jonspalmer. I think my ideals here are influenced by the bias I've built up around implementing ViewComponent in my app, so I can understand if they don't extend to more cases. 

It might be good to have the suffix as a configurable default, so that the decision around how component names are generated only needs to be made once and not each time the generator is run.

**Comment by Spone** [comment]
> It might be good to have the suffix as a configurable default, so that the decision around how component names are generated only needs to be made once and not each time the generator is run.

I agree, and I think that any flag that is added to the generator should also be configurable once, project-wide (see #623).

**Comment by jonspalmer** [comment]
Looking at this from a slightly different perspective how do we think this should look if we were hooking into Rails scaffolding?

Suppose our push is that VIew Components should be used to replace the view layer of Rails entirely. Controller-actions should have a dedicated ViewComponent that they render directly. Today Rails scaffold looks like this:

```sh
bin/rails generate scaffold HighScore game:string score:integer
    invoke  active_record
    create    db/migrate/20190416145729_create_high_scores.rb
    create    app/models/high_score.rb
    invoke    test_unit
    create      test/models/high_score_test.rb
    create      test/fixtures/high_scores.yml
    invoke  resource_route
     route    resources :high_scores
    invoke  scaffold_controller
    create    app/controllers/high_scores_controller.rb
    invoke    erb
    create      app/views/high_scores
    create      app/views/high_scores/index.html.erb
    create      app/views/high_scores/edit.html.erb
    create      app/views/high_scores/show.html.erb
    create      app/views/high_scores/new.html.erb
    create      app/views/high_scores/_form.html.erb
    invoke    test_unit
    create      test/controllers/high_scores_controller_test.rb
    create      test/system/high_scores_test.rb
    invoke    helper
    create      app/helpers/high_scores_helper.rb
    invoke      test_unit
    invoke    jbuilder
    create      app/views/high_scores/index.json.jbuilder
    create      app/views/high_scores/show.json.jbuilder
    create      app/views/high_scores/_high_score.json.jbuilder
    invoke  assets
    invoke    scss
    create      app/assets/stylesheets/high_scores.scss
    invoke  scss
    create    app/assets/stylesheets/scaffolds.scss
```

What would that look like with ViewComponents?


```sh
bin/rails generate scaffold HighScore game:string score:integer
    invoke  active_record
    create    db/migrate/20190416145729_create_high_scores.rb
    create    app/models/high_score.rb
    invoke    test_unit
    create      test/models/high_score_test.rb
    create      test/fixtures/high_scores.yml
    invoke  resource_route
     route    resources :high_scores
    invoke  scaffold_controller
    create    app/controllers/high_scores_controller.rb
    invoke    components
    create      app/components/high_scores_component.rb # index
    create      app/components/high_scores_component.html.erb
    create      app/components/high_score_component.rb #show
    create      app/components/high_score_component.html.erb
    create      app/components/high_score_form_component.rb #new/edit
    create      app/components/high_score_form_component.html.erb
    invoke    test_unit
    create      test/controllers/high_scores_controller_test.rb
    create      test/components/high_scores_component_test.rb
    create      test/components/high_score_component_test.rb
    create      test/components/high_score_form_component_test.rb
    create      test/system/high_scores_test.rb
    invoke    helper
    create      app/helpers/high_scores_helper.rb
    invoke      test_unit
    invoke    jbuilder
    create      app/views/high_scores/index.json.jbuilder
    create      app/views/high_scores/show.json.jbuilder
    create      app/views/high_scores/_high_score.json.jbuilder
    invoke  assets
    invoke    scss
    create      app/assets/stylesheets/high_scores.scss
    invoke  scss
    create    app/assets/stylesheets/scaffolds.scss
 ```
 
 In the above it seems pretty natural/desirable to have a suffix.

**Comment by boardfish** [comment]
IMO the most intuitive thing would be to reflect the structure of current Rails views as closely as possible, e.g.

```
app/views/high_scores/show/...
app/views/high_scores/show.rb
app/views/high_scores/index/...
app/views/high_scores/index.rb
```

...and so on. Note that the components are stored in `app/views` as we'd hope to see through in #618. The corresponding component constants would be under the `HighScores` namespace in the top level. 

As a nice side-effect, plural namespaces would potentially lead to less clashes as constants tend to be named singularly.

**Comment by jonspalmer** [comment]
@boardfish I understand the logic of that suggestion but honestly a plethora of index.html.erb littering a large code base is one of the most irritating things about the Rails view layer as grepping by file name just sucks. I'm unconvinced that having lots of index.rb files representing components is particularly great. I do see how the folder structure is an advantage.

**Comment by boardfish** [comment]
That's a valid concern, but I think changes to the default view scaffold are more of a question for Rails than ViewComponent. In the meantime, I think it makes some sense for us to follow the existing structure, since that creates the least surprise. I'll refer back to this discussion in #618 as it'll help to guide that, but it's tangential to the ADR. 

That having been said, I do feel that the decisions on these two are coupled together. What we choose to do here affects the scaffold output as we'd hope to see in #618. Or, from a better angle, the best path to #618 influences the structure of component names in this PR.

**Comment by joelhawksley** [comment]
@boardfish @Spone @jonspalmer thank you all for the thoughtful discussion here!

I'm going to close this proposal for now.

After giving it some more thought, I don't feel strongly enough about making these changes at this point. I appreciate the perspective you all have provided. 

I'll likely follow up with a light update to the documentation about how the suffix might be removed in some use cases.

**Pull request closed without merging**
