### PR TITLE
Use new dark mode image syntax for README logo

### PR DESCRIPTION
**Pull request by dylanatsmith**
GitHub [just released](https://github.blog/changelog/2022-08-15-specify-theme-context-for-images-in-markdown-ga/) better theme support for images in Markdown.

This PR updates the README to use the new syntax.

### CODE REVIEW

**Review by keithamus — APPROVED** [review]
:+1:

**Review by joelhawksley — CHANGES_REQUESTED** [review]
@Spone just tried this. It does not work on GitHub mobile, at least on android. We reverted it: https://github.com/github/view_component/pull/1480

**Comment by dylanatsmith** [comment]
> It does not work on GitHub mobile, at least on android.

Womp womp.

Have we filed a bug?

**Comment by joelhawksley** [comment]
> > It does not work on GitHub mobile, at least on android.
> 
> Womp womp.
> 
> Have we filed a bug?

I've brought it up internally. I don't think a fix is coming in the near future.

**Pull request closed without merging**
