### PR TITLE
Update logo code in README

### PR DESCRIPTION
**Pull request by Spone**
### What are you trying to accomplish?

Make the README logo light mode / dark mode friendly (it has initially been done in #1169 but this approach is now deprecated)

### What approach did you choose and why?

The new recommended approach: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

### CODE REVIEW

**Review by joelhawksley — APPROVED** [review]

**Comment by Spone** [comment]
This doesn't work in the GitHub Android app though...

**Comment by joelhawksley** [comment]
@Spone do you think we should revert, then?

**Comment by Spone** [comment]
> @Spone do you think we should revert, then?

Could you find out if a fix is coming on the mobile app side? If not, I'd say we should revert for now.

**Comment by joelhawksley** [comment]
@Spone it's on our radar but I think we should revert this for now.

**Pull request merged**
