### PR TITLE
Declare Capybara as a development dependency

### PR DESCRIPTION
**Pull request by n-rodriguez**
Fix https://github.com/github/view_component/issues/292

### CODE REVIEW

**Comment by jcoyne** [comment]
I believe the test helper depends on capybara matchers. https://github.com/github/view_component/blob/master/lib/view_component/test_helpers.rb#L3
  It would be good to document that you need to include capybara in your gemfile if you want to also use that helper.

**Comment by joelhawksley** [comment]
@jcoyne I was wondering if that would be an issue. I wouldn't want to break the existing test helper functionality.

**Comment by jcoyne** [comment]
@joelhawksley It's likely that your application already had capybara as a dependency, in which case it's not a problem.  You could test for `defined? Capybara` in TestHelpers and emit a warning about adding it to the "Gemfile" if it isn't

**Comment by joelhawksley** [comment]
@jcoyne if we're going to expect folks to change their Gemfiles, I'm not sure this change is worth it, IMO.

**Comment by n-rodriguez** [comment]
> It would be good to document that you need to include capybara in your gemfile if you want to also use that helper.

sure

**Comment by n-rodriguez** [comment]
> You could test for `defined? Capybara` in TestHelpers and emit a warning about adding it to the "Gemfile" if it isn't

:+1:

**Comment by joelhawksley** [comment]
@n-rodriguez will this require users of the library to change their Gemfiles to use the test helpers? If so, I'm going to recommend that we stick with our current dependency on Capybara.

**Comment by md5** [comment]
Would it be possible to move the test helpers to a separate gem, say `view_component-test_helpers`, and have the runtime dependency for `capybara` live there?

Then in the docs, you could change to this:

> In `Gemfile`, add:
> 
> ```
> gem "view_component"
> gem "view_component-test_helpers", group: :development
> ```

**Comment by joelhawksley** [comment]
@md5 can you provide an example of an existing (preferably popular) project that has a separate gem for test helpers? While that solution makes sense, it feels cumbersome to me.

@n-rodriguez what is the concern with having `capybara` in production? Is it the unnecessary increase in bundle size?

**Comment by md5** [comment]
> @md5 can you provide an example of an existing (preferably popular) project that has a separate gem for test helpers? While that solution makes sense, it feels cumbersome to me.

I think `rack-test` is probably the best example that I'm seeing, although `Rack::MockRequest` and `Rack::MockResponse` are built into `rack` itself and autoloaded from `rack/mock`.

Speaking for myself, I don't find the `capybara` dependency all that objectionable, since it has pretty tame dependencies itself, but it definitely isn't needed in production. I would say the argument is not just bundle size, but having any code above and beyond what's actually needed to run the app. There's obviously a slippery slope here, since there may be parts of `rails` that people aren't using or other cases where they only use a small subset of a monolithic gem's functionality, but `capybara` is a library for testing and nothing else.

**Comment by rmacklin** [comment]
PSA: #298 has been merged so capybara is no longer a dependency.

**Comment by joelhawksley** [comment]
Closing in favor of https://github.com/github/view_component/pull/298. Thank you for your work on this PR @n-rodriguez @md5 @jcoyne !

**Pull request closed without merging**
