### PR TITLE
Update bundler version to 2.1.4

### PR DESCRIPTION
**Pull request by dmarcoux**
### Summary

This updates bundler to the latest version.

### Other Information

I don't believe this should be in the `CHANGELOG.md`.

### CODE REVIEW

**Comment by dmarcoux** [comment]
The CI runs for `rails 5.0.0` depends on `bundler < 2.0`, so this prevents using a more modern version of bundler.

**Comment by joelhawksley** [comment]
@dmarcoux could we potentially load a different version of bundler depending on the rails version?

**Comment by dmarcoux** [comment]
Oh right, I might have been a bit too strict with my versioning in the gemspec.

**Comment by dmarcoux** [comment]
I'll have to try in another PR since I cannot reopen this PR. Whoopsie!

**Pull request closed without merging**
