### PR TITLE
Lazily evaluate content instead of eagerly evaluating it

### PR DESCRIPTION
**Pull request by BlakeWilliams**
This changes `content` to load only when a component's `render?`
predicate method returns true. The `render?` method can still access
`content`, which will cause it to be evaluated.

~This shouldn't be a breaking change for components themselves, but
attempting to access a slot in `before_render` or `render?` may no
longer work.~

This is an alternative approach to https://github.com/github/view_component/pull/559 (but doesn't remove the value of the conversation happening there, imo) and may at least partially close https://github.com/github/view_component/issues/558

### CODE REVIEW

**Comment by BlakeWilliams** [comment]
I merged https://github.com/github/view_component/pull/576 into this PR to highlight the performance aspect of this change. If this gets merged, I think that PR can be closed.

**Comment by BlakeWilliams** [comment]
Just pushed up a change that makes accessing slots from `render?` and `before_render` continue to work without having to manually evaluate content.

Here's the benchmark:

Screen Shot 2021-02-10 at 5 39 00 PM

We may have gotten a tiny bit slower, but not enough to be a concern.

**Comment by BlakeWilliams** [comment]
I just ran this locally against the `primer/view_components` test suite and getting test failures, presumably due to Slots v1? Looking now though.

**Comment by BlakeWilliams** [comment]
Just pushed up https://github.com/github/view_component/pull/613/commits/35e8d6cd037d8fa16266c127c81b83bb77d1dc4d to resolve that issue.

**Review by joelhawksley — APPROVED** [review]
Do we need a CHANGELOG here?

**Comment by BlakeWilliams** [comment]
Yep! Adding one now.

**Comment by patchwork-her** [comment]
Stop this mess now! Look... These are my personal email addresses you are taking as your own to do with my personal content as you please and trying your best to deny my rights to my personal property. I can make a police report if necessary. Which do you prefer? Fix this now and give me my full access to my personal gmail accts patchesrich1977@gmail, patchesrich20@gmail.com, lilpr1977@gmail.com, lilpr1977@gmail.com, patches77@hyptic.cryptic.com, lilpr1977@hyptic.cryptic.com, patchespledger@gmail.com, hyptic.cryptic@outlook.net hyptic_cryptic@outlook.net

**Comment by patchwork-her** [comment]
I can't access most of my emails anymore because of the last several months of commits done here on github.

**Comment by jhirbour** [comment]
@patchwork-her you should contact support@github.com

**Review by joelhawksley — APPROVED** [review]

**Pull request merged**
