### PR TITLE
[WIP] Use ActionView::ViewPaths to manage views with ViewComponent

### PR DESCRIPTION
**Pull request by nicolas-brousse**
### Summary

This is a work in progress. I only try locally on an existing project for now.

This change attempt to make `#initialize` method optional in components (as discuss in https://github.com/github/view_component/issues/236#issuecomment-594642108) by switching rendering system on `ActionView::ViewPaths`.

### Notes
* Should we have a custom class for `ActionView::MissingTemplate` exception?
* `ViewComponent::ViewPaths` has implemented the scoped view_paths by class on Rails 6.0.0.

### CODE REVIEW

**Comment by joelhawksley** [comment]
@nicolas-brousse is this still a change you'd like to try and land? If so, this PR will need some updates to catch up with `master`. Thank you for taking the time to work on it either way!

**Comment by nicolas-brousse** [comment]
@joelhawksley is this still something interesting for `view_component`?

If yes, then I think I could take some time to resolve conflicts. Or even restart in a new fresh PR. The thing is that I may need some help for some parts, since I'm not an expert of ActionView.

I also have to go deeper about rails incompatibilities, for versions before 6.0. Since Rails 6.0 implemented [some new interesting code](https://github.com/rails/rails/blob/v6.0.0/actionview/lib/action_view/view_paths.rb#L40-L53), that does not exists in [Rails 5.1](https://github.com/rails/rails/blob/v5.2.0/actionview/lib/action_view/view_paths.rb).

Let me know 🙂

**Comment by joelhawksley** [comment]
@nicolas-brousse given that we have removed the initializer requirement another way: https://github.com/github/view_component/pull/277, do you think these changes would benefit the library? If so, how?

**Comment by nicolas-brousse** [comment]
@joelhawksley Oh! I totally missed the #277 changes.

Since the main idea was:
> This change attempt to make `#initialize` method optional in components

And not sure having multiple view paths is a real needs actually. So lets close this PR for now.
If its something that sounds useful in the future, then I may help.

I guess keeping `view_component` light and simple sounds better 🙂

**Pull request closed without merging**
