### PR TITLE
Fix typo in the README

### PR DESCRIPTION
**Pull request by Hirurg103**

### CODE REVIEW

**Comment by Hirurg103** [comment]
Hi @joelhawksley, thank you for approving my PR. I don't think that this small typo fix deserves me to be in the list of collaborators 😏

**Comment by Hirurg103** [comment]
Hi @joelhawksley, I don't think that this small typo fix deserves me to be in the list of collaborators 😏

**Comment by Hirurg103** [comment]
Hi @joelhawksley, I think that this typo fix is too minor to add me to the list of contributors. Is it possible to omit step no.6 of the [submitting a PR guide](https://github.com/github/view_component/blob/master/CONTRIBUTING.md#submitting-a-pull-request)?

**Comment by joelhawksley** [comment]
@Hirurg103 your call! Any contribution counts in my book :)

**Pull request merged**
