### PR TITLE
Add frozen_string_literal to Component template

### PR DESCRIPTION
**Pull request by maxbeizer**
@joelhawksley how do you feel about this? I certainly can't think of a reason not to do. Perhaps not everyone adds this?

It's been around a while https://bugs.ruby-lang.org/issues/8976

### CODE REVIEW

**Review by joelhawksley — APPROVED** [review]

**Comment by joelhawksley** [comment]
Mind adding a changelog entry?

**Comment by maxbeizer** [comment]
Yeah I figured I'd wait to see if you liked this change first. I'll get to it asap

**Comment by maxbeizer** [comment]
@joelhawksley Changelog added. I went ahead and squashed it all together too 🎁

**Review by joelhawksley — APPROVED** [review]

**Comment by maxbeizer** [comment]
❤️🧡💛💚💙💜🖤

**Pull request merged**
