### PR TITLE
Add HappyCo to the list of companies using ViewComponent

### PR DESCRIPTION
**Pull request by joshuaclayton**
### What are you trying to accomplish?

Add [HappyCo](https://happy.co) to the list of companies using ViewComponent. Thanks for considering!

### What approach did you choose and why?

Opening a PR to the repo is the current recommended way to add to the list of companies.

### Anything you want to highlight for special attention from reviewers?

This maintains alphabetical ordering.

### CODE REVIEW

**Review by BlakeWilliams — APPROVED** [review]
LGTM, could you add an entry to the changelog to make CI happy?

also hey! nice to see you here! 🙂

**Comment by joshuaclayton** [comment]
@BlakeWilliams well hello!

Sure thing; I've pushed 7d5f90f0ac94a3822dd14e14596f3bb04f00db89 to address. I wasn't sure if I should (using https://github.com/github/view_component/pull/1392/files as a reference) but happy to get CI green 😅

**Comment by BlakeWilliams** [comment]
Thanks! We've gone back-and-forth on our changelog practices a few times, but we landed on "all changes need an entry", even for small changes like this.

Great to see y'all are using ViewComponent, I'd love to hear how it's treating y'all some time.

**Comment by joshuaclayton** [comment]
@BlakeWilliams with Tailwind and Stimulus, it's just incredible (it would be without that, sure, but in conjunction IMO they all elevate each other higher).

I'll have to dig through how others have used it (I know there's a bunch of resources [here](https://viewcomponent.org/resources.html#articles), but I'm backed up on other reading right now) and then write up if we're doing anything differently. One pattern I've personally enjoyed is making the constructor private and moving towards more of a builder pattern (e.g. `PillComponent.green` versus `PillComponent.new(color: :green)`) and isolating combinations that way rather than passing in args. In typing this out, I guess passing in different strategies could do the same thing for more complicated pieces too.

At any rate, thanks for getting this merged and the amazing work the team has done here. It's been a huge productivity and modularity boost!

**Pull request merged**
