### PR TITLE
Versioned documentation

### LINKED ISSUE #1151: Versioned documentation
## Feature request

As a developer reading the ViewComponent documentation, it is unclear whether there are unreleased features in the docs.

### Motivation

We've seen some issues here and there of folks being mislead by our documentation when unreleased changes were described in the docs. 

### Proposed solution

I could see us solving this a couple ways. We could only publish the docs when a release is cut, we could version the docs (see https://glebbahmutov.com/blog/versioned-doc-pages/, or perhaps we could start with a disclaimer that the docs are for the `main` branch.

### PR DESCRIPTION
**Pull request by Spone**
### Summary

- [x] Remove warning about running docs:build task in CI
- [x] Remove mention of docs:build in Contributing docs
- [x] Build the API docs when releasing a new version
- [x] Update the viewcomponent.org website only when releasing a new version

Close #1151

### CODE REVIEW

**Comment by Spone** [comment]
I'm not sure how to achieve the last item :thinking:

**Comment by Spone** [comment]
If I understand Github Pages configuration correctly, to update the viewcomponent.org website only when releasing a new version, we need to configure the website to deploy from a specific branch (instead of `main`), and update this branch as part of the release process. What do you think @BlakeWilliams @joelhawksley? Can you set this up?

**Comment by boardfish** [comment]
I figure we can still deploy from `main` if it's only `script/release` that will update the docs site. That also gives us the flexibility to update the docs site if there's something that immediately affects all ViewComponent users.

**Comment by Spone** [comment]
> I figure we can still deploy from `main` if it's only `script/release` that will update the deployed code for the docs site. That also gives us the flexibility to update the docs site if there's something that immediately affects all ViewComponent users. 

Can you point to where the docs site is generated? I think it's handled by GitHub Pages.

**Comment by boardfish** [comment]
`rake docs:build` updates the contents of the docs site. I assume from there, GitHub Pages then uses the contents of the `docs` folder to generate and deploy a Jekyll site. Right now we encourage folks to run the Rake task as part of their PR if they update the documentation, meaning any docs changes are deployed once their PR is merged to `main`. This PR removes that requirement and runs the task in `script/release`, meaning the docs are only changed when a new release is made.

**Comment by Spone** [comment]
The `docs:build` task only updates `docs/api.md` (documentation generated with YARD). But the rest of the documentation is based on the `*.md` files placed in `docs`, and as far as I know we can't trigger their update manually: Github Pages will automatically publish what's in `docs` for the configured branch, on every push. That's why I suggested using a different branch for Github Pages.

**Comment by boardfish** [comment]
Ah, gotcha - I admittedly wasn't thinking about the rest of the documentation as the last work I did around there was only linked to `api.md`, apologies. You're right that we would need another branch.

**Comment by joelhawksley** [comment]
> What do you think @BlakeWilliams @joelhawksley? 

@Spone that sounds good to me. Let me know what changes we need to make as admins ❤️

**Comment by Spone** [comment]
> @Spone that sounds good to me. Let me know what changes we need to make as admins heart

I think we need to pick a name for the documentation branch (`gh-pages`, which seems to be the convention ? `docs` ?)

Then create this branch and configure the repository to use it as Github Pages source: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

**Comment by joelhawksley** [comment]
@spone sorry for the delay in getting back to you here. Perhaps it would be best to do a quick 🍐 on this to get it all lined up? Send me an email ❤️

**Comment by Spone** [comment]
@joelhawksley all checks have passed, the PR is just missing your review :)

**Review by joelhawksley — APPROVED** [review]

**Pull request merged**
