### PR TITLE
Deprecate engine loading manually

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

Currently we support engine loading both manually and automatically.

However, considering maintainability, it seems better that manually loading be deprecated from v3.0.0.

In this change, it deprecates them and displays deprecation warning.

### Demo

If it would like to confirm deprecation warning, please change `test/sandbox/config/application.rb` like this:

```diff
 require "action_view/railtie"
 require "sprockets/railtie"

-require "view_component"
+require "view_component/engine"

 require "haml"
 require "slim"
```

Then run `bundle exec rake test`, and check warning message:

```diff
  % bundle exec rake test
+ DEPRECATION WARNING: This manually engine loading is deprecated and will be removed in v3.0.0. Remove `require "view_component/engine"`. (called from require at /home/yhirano55/src/github.com/yhirano55/view_component/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.0.beta5/lib/zeitwerk/kernel.rb:35)
+ DEPRECATION WARNING: This manually engine loading is deprecated and will be removed in v3.0.0. Remove `require "view_component/engine"`. (called from require at /home/yhirano55/src/github.com/yhirano55/view_component/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.0.beta5/lib/zeitwerk/kernel.rb:35)
  DEPRECATION WARNING: `preview_path` will be removed in v3.0.0. Use `preview_paths` instead. (called from <top (required)> at /home/yhirano55/src/github.com/yhirano55/view_component/test/sandbox/config/environment.rb:7)
```

### In v3.0.0 release...

The following changes are required:

1. `lib/view_component.rb`

```diff
   autoload :Translatable
 end

-if defined?(ViewComponent::Engine)
-  ActiveSupport::Deprecation.warn(
-    "This manually engine loading is deprecated and will be removed in v3.0.0. " \
-    "Remove `require \"view_component/engine\"`."
-  )
-elsif defined?(Rails::Engine)
-  require "view_component/engine"
-end
+require "view_component/engine" if defined?(Rails::Engine)
```

2. `lib/view_component/engine.rb`

```diff
     end
   end
 end
-
-unless defined?(ViewComponent::Base)
-  ActiveSupport::Deprecation.warn(
-    "This manually engine loading is deprecated and will be removed in v3.0.0. " \
-    "Remove `require \"view_component/engine\"`."
-  )
-
-  require "view_component"
-end
```

### CODE REVIEW

**Comment by yhirano55** [comment]
Oops...CI was failed. I'll add test cases in a few days.

**Comment by yhirano55** [comment]
For example, I added the deprecation test like this:

```ruby
# frozen_string_literal: true

require "test_helper"

class DeprecationTest < ActiveSupport::TestCase
  test "require 'view_component/engine' manually" do
    assert_deprecated(/This manually engine loading is deprecated and will be removed in v3.0.0. Remove `require "view_component\/engine"`./) do
      require "view_component/engine"
    end
  end
end
```

And this test is passed if it run with single file.

```
% bundle exec ruby -I test test/view_component/deprecation_test.rb
Run options: --seed 11569

# Running:

.

Finished in 0.033364s, 29.9723 runs/s, 59.9447 assertions/s.

1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

But in case of `rake test`, this test is failed.

I need time to solve this problem.

If it have a hint or how to resolve it, please advise me...

**Comment by joelhawksley** [comment]
@yhirano55 it looks like the `coverage` check is failing. I'm OK with `nocov`ing those lines if you'd like.

**Comment by yhirano55** [comment]
@joelhawksley Thank you for your advice! I didn't know about `nocov` :sweat_drops:  I'm going to add `nocov` today.

**Comment by yhirano55** [comment]
@joelhawksley The CI was passed. Would you please code-review this pull request?

**Review by joelhawksley — APPROVED** [review]

**Pull request merged**
