### PR TITLE
Changelog requirement

### PR DESCRIPTION
**Pull request by joelhawksley**
This PR introduces a build that ensures folks include CHANGELOG entries in their PRs so that reviewers don't have to ask for them. I also took the liberty of changing our CI configuration to only run on PRs, not all pushes.

### CODE REVIEW

**Comment by Spone** [comment]
@joelhawksley is there a way to skip this check for tiny changes (such as https://github.com/github/view_component/pull/984)?

**Comment by joelhawksley** [comment]
@Spone It's probably possible! One intent here was to force us to recognize all contributions, no matter how small. Perhaps I should update the contribution guide to mention that?

**Review by BlakeWilliams — APPROVED** [review]
I'm a fan of this change, 👍 to trying this out and seeing how it goes.

**Comment by joelhawksley** [comment]
@Spone I added a note to that effect: https://github.com/github/view_component/pull/989

**Pull request merged**
