### PR TITLE
fix bug where Compiler was not available

### LINKED ISSUE #1468: NameError: uninitialized constant ViewComponent::Compiler
### Steps to reproduce

1. Install the `view_component` gem, version 2.66
2. Run `bin/rails db:seed`

### Expected behavior

It should seed the database.

### Actual behavior

An error is thrown:

```bash
$ bin/rails db:seed
rails aborted!
NameError: uninitialized constant ViewComponent::Compiler

      ViewComponent::Compiler.mode = if Rails.env.development? || Rails.env.test?
                   ^^^^^^^^^^
Did you mean?  Complex
/workspace/web/config/environment.rb:5:in `<main>'
Tasks: TOP => db:seed => db:load_config => environment
(See full trace by running task with --trace)
```

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2p20

**Gem version**: 2.66

### PR DESCRIPTION
**Pull request by joelhawksley**
### What are you trying to accomplish?

Fix #1468

### What approach did you choose and why?

I required the file in question.

### Anything you want to highlight for special attention from reviewers?

No.

### CODE REVIEW

**Review by camertron — APPROVED** [review]
Weird, I wonder why the `autoload` in lib/view_component.rb doesn't handle this?

**Comment by joelhawksley** [comment]
> Weird, I wonder why the `autoload` in lib/view_component.rb doesn't handle this?

I wonder too. I notice that some files are required in `base` and some are not. Still, I'm preferring to get folks unblocked here while we investigate.

**Review by BlakeWilliams — APPROVED** [review]

**Comment by Spone** [comment]
This kind of issue should no longer happen when moving to Zeitwerk #1378 :)

**Comment by joelhawksley** [comment]
@Spone agreed, want to add it?

**Comment by Spone** [comment]
@joelhawksley I spent some time on it already, but it's not working yet :)

**Pull request merged**
