### PR TITLE
Can set custom templates explicitly now.

### PR DESCRIPTION
**Pull request by vikks**
### Summary

When working with many components, having an option to name custom templates and set them in 
the components makes editing and fixing code much easier rather than having to double check every time
a template file is opened for editing.

```ruby
# app/components/image/component.rb

class Image::Component < ViewComponent::Base
  # Uses app/components/image/image_template.html.erb
  template "image_template"
end
```
```ruby
# app/components/image/component.rb

class Button::Component < ViewComponent::Base
  # Uses the default app/components/button/component.html.erb
end
```
```
components/
   button/
     component.html.erb
     component.rb
   image/
     image_template.html.erb
     component.rb  
     controller.js
```

### Other Information

Added test files for CustomTemplate component and its corresponding html template.

### CODE REVIEW

**Review by Sergei2208 — COMMENTED** [review]
test/view_component/view_component_test.rb

**Comment by Sergei2208** [comment]
Good

**Comment by Sergei2208** [comment]
Good

**Comment by joelhawksley** [comment]
@vikks thank you for taking the time to open a PR with this idea!

Per https://github.com/github/view_component/issues/670, we are planning to remove the recommendation for the `Component` suffix naming convention. Given that context, I don't think we should add this API to the project. 

I would be open to making it possible to change configure this option via a gem, in a similar manner to @boardfish's approach in https://github.com/github/view_component/issues/670#issuecomment-822349700.

I'm going to go ahead and close this PR for housekeeping purposes, but I am happy to continue discussing it. 

Please do continue to share ideas you have for ViewComponent- the project is built through the work of folks from the community just like you ❤️

**Pull request closed without merging**
