### PR TITLE
Enable search for docs site

### LINKED ISSUE #864: Add search to docs site
### Problem

The docs site does not have search functionality. [Just the Docs](https://pmarsceill.github.io/just-the-docs/) has it built in.

### Solution

Add search to the docs site ❤️

### PR DESCRIPTION
**Pull request by dmarcoux**
### Summary

Keeping the defaults from Just the Docs:
https://github.com/pmarsceill/just-the-docs/blob/e8424986370bef104e680e1443a83e475d2fead7/docs/search.md

Closes #864

### Other Information

Preview:

view_component-search

### CODE REVIEW

**Review by schmelto — APPROVED** [review]

**Comment by Spone** [comment]
I love the diff :laughing:

**Review by joelhawksley — APPROVED** [review]
Wow, I thought this would take more work! I'm not sure why Pages Previews aren't working here, so let's just merge and see what happens 😅

**Comment by joelhawksley** [comment]
Looks like that did the trick!

**Comment by dmarcoux** [comment]
I was also pleasantly surprised by the "work" needed to do this! :smile:

**Pull request merged**
